### PR TITLE
fix #33 by composing .zip url, switch to https dub-registry url

### LINKED ISSUE #33: Build error: Key not found: downloadUrl
## CMakeLists.txt

```cmake
# A more complex library test.
file(GLOB SRC_LIST "*.d")

include(UseDub)

DubProject_Add(vibe-d ~0.9.2)

add_executable(app_10 ${SRC_LIST})
add_test(app_10 app_10)
```

## main.d

```d
module main;

import vibe.core.core;
import vibe.http.fileserver;
import vibe.http.server;

void main()
{
    listenHTTP(new HTTPServerSettings(":9090"), serveStaticFiles("./"));
    runApplication();
}
```

```
2020-09-24 11:17:46 ~/code/d/tests-cmake-d/b
$ cmake -DCMAKE_MODULE_PATH:PATH=$SETUP/cmake-d/cmake-d ..
-- The C compiler identification is GNU 9.3.0
-- The D compiler identification is DigitalMars
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working D compiler: /usr/bin/dmd
-- Check for working D compiler: /usr/bin/dmd -- works
-- Detecting D compiler ABI info
-- Detecting D compiler ABI info - done
std.json.JSONException@std/json.d(627): Key not found: downloadUrl
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x5626c25b248f]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x5626c25b2505]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x5626c2582f09]
??:? _Dmain [0x5626c250a307]
CMake Error at /opt/dev-setup/cmake-d/cmake-d/UseDub.cmake:70 (include):
  include could not find load file:

    /home/arun/code/d/tests-cmake-d/b/UseDub/vibe-d.cmake
Call Stack (most recent call first):
  app_10/CMakeLists.txt:6 (DubProject_Add)


-- Configuring incomplete, errors occurred!
See also "/home/arun/code/d/tests-cmake-d/b/CMakeFiles/CMakeOutput.log".
2020-09-24 11:18:13 ~/code/d/tests-cmake-d/b
$
```

### PR DESCRIPTION
**Pull request by Boris-Barboris**

### CODE REVIEW

**Comment by dcarp** [comment]
LGTM

**Review by dcarp — CHANGES_REQUESTED** [review]

**Comment by Boris-Barboris** [comment]
How do I abort all this review stuff?

**Comment by dcarp** [comment]
> How do I abort all this review stuff? Pressed the wrong button apparently.

You don't need to do anything. If possible, please address the questions.

**Review by Boris-Barboris — COMMENTED** [review]
> 
> 
> > How do I abort all this review stuff? Pressed the wrong button apparently.
> 
> You don't need to do anything. If possible, please address the questions.

I believe I did, look at the commends below yours.

**Review by dcarp — APPROVED** [review]
LGTM, thanks for the contribution!

**Pull request merged**
